version: '3.8'

services:
  app:
    image: frontend
    build:
      context: frontend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - frontend-nodemod:/usr/src/app/node_modules
      - ./frontend/:/usr/src/app

    ports:
      - 5173:5173
    # environment:
    #   - VITE_BACKEND_URL=http://localhost:8080

  server:
    image: server
    build:
      context: backend
      dockerfile: dev.Dockerfile
    ports:
      - 8000:8000
    # volumes:
    #   - ./backend/:/usr/src/app

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
volumes:
  # backend-nodemod:
  frontend-nodemod:
