services:
  app:
    image: backend
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    # volumes:
    #   - /usr/src/app

    ports:
      - 8080:8080
    container_name: backend

volumes:
  backend-nodemod:
