name: CI Build and Test Backend

on:
  push:
    branches:
      - dev
    paths:
      - 'backend/**'
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and Tests with Maven
        run: mvn -ntp -B verify
